In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [78]:
data = pd.read_csv("../datasets/wine.csv")

In [79]:
data.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [80]:
data.isna().sum()

Wine                    0
Alcohol                 0
Malic.acid              0
Ash                     0
Acl                     0
Mg                      0
Phenols                 0
Flavanoids              0
Nonflavanoid.phenols    0
Proanth                 0
Color.int               0
Hue                     0
OD                      0
Proline                 0
dtype: int64

In [81]:
x = data.iloc[:,1].reset_index().values
y = data.iloc[:,2:]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [82]:
model = LinearRegression()

In [83]:
x

array([[  0.  ,  14.23],
       [  1.  ,  13.2 ],
       [  2.  ,  13.16],
       [  3.  ,  14.37],
       [  4.  ,  13.24],
       [  5.  ,  14.2 ],
       [  6.  ,  14.39],
       [  7.  ,  14.06],
       [  8.  ,  14.83],
       [  9.  ,  13.86],
       [ 10.  ,  14.1 ],
       [ 11.  ,  14.12],
       [ 12.  ,  13.75],
       [ 13.  ,  14.75],
       [ 14.  ,  14.38],
       [ 15.  ,  13.63],
       [ 16.  ,  14.3 ],
       [ 17.  ,  13.83],
       [ 18.  ,  14.19],
       [ 19.  ,  13.64],
       [ 20.  ,  14.06],
       [ 21.  ,  12.93],
       [ 22.  ,  13.71],
       [ 23.  ,  12.85],
       [ 24.  ,  13.5 ],
       [ 25.  ,  13.05],
       [ 26.  ,  13.39],
       [ 27.  ,  13.3 ],
       [ 28.  ,  13.87],
       [ 29.  ,  14.02],
       [ 30.  ,  13.73],
       [ 31.  ,  13.58],
       [ 32.  ,  13.68],
       [ 33.  ,  13.76],
       [ 34.  ,  13.51],
       [ 35.  ,  13.48],
       [ 36.  ,  13.28],
       [ 37.  ,  13.05],
       [ 38.  ,  13.07],
       [ 39.  ,  14.22],
       [ 40.  ,  13.56],
       [ 41.  ,  13.41],
       [ 42.  ,  13.88],
       [ 43.  ,  13.24],
       [ 44.  ,  13.05],
       [ 45.  ,  14.21],
       [ 46.  ,  14.38],
       [ 47.  ,  13.9 ],
       [ 48.  ,  14.1 ],
       [ 49.  ,  13.94],
       [ 50.  ,  13.05],
       [ 51.  ,  13.83],
       [ 52.  ,  13.82],
       [ 53.  ,  13.77],
       [ 54.  ,  13.74],
       [ 55.  ,  13.56],
       [ 56.  ,  14.22],
       [ 57.  ,  13.29],
       [ 58.  ,  13.72],
       [ 59.  ,  12.37],
       [ 60.  ,  12.33],
       [ 61.  ,  12.64],
       [ 62.  ,  13.67],
       [ 63.  ,  12.37],
       [ 64.  ,  12.17],
       [ 65.  ,  12.37],
       [ 66.  ,  13.11],
       [ 67.  ,  12.37],
       [ 68.  ,  13.34],
       [ 69.  ,  12.21],
       [ 70.  ,  12.29],
       [ 71.  ,  13.86],
       [ 72.  ,  13.49],
       [ 73.  ,  12.99],
       [ 74.  ,  11.96],
       [ 75.  ,  11.66],
       [ 76.  ,  13.03],
       [ 77.  ,  11.84],
       [ 78.  ,  12.33],
       [ 79.  ,  12.7 ],
       [ 80.  ,  12.  ],
       [ 81.  ,  12.72],
       [ 82.  ,  12.08],
       [ 83.  ,  13.05],
       [ 84.  ,  11.84],
       [ 85.  ,  12.67],
       [ 86.  ,  12.16],
       [ 87.  ,  11.65],
       [ 88.  ,  11.64],
       [ 89.  ,  12.08],
       [ 90.  ,  12.08],
       [ 91.  ,  12.  ],
       [ 92.  ,  12.69],
       [ 93.  ,  12.29],
       [ 94.  ,  11.62],
       [ 95.  ,  12.47],
       [ 96.  ,  11.81],
       [ 97.  ,  12.29],
       [ 98.  ,  12.37],
       [ 99.  ,  12.29],
       [100.  ,  12.08],
       [101.  ,  12.6 ],
       [102.  ,  12.34],
       [103.  ,  11.82],
       [104.  ,  12.51],
       [105.  ,  12.42],
       [106.  ,  12.25],
       [107.  ,  12.72],
       [108.  ,  12.22],
       [109.  ,  11.61],
       [110.  ,  11.46],
       [111.  ,  12.52],
       [112.  ,  11.76],
       [113.  ,  11.41],
       [114.  ,  12.08],
       [115.  ,  11.03],
       [116.  ,  11.82],
       [117.  ,  12.42],
       [118.  ,  12.77],
       [119.  ,  12.  ],
       [120.  ,  11.45],
       [121.  ,  11.56],
       [122.  ,  12.42],
       [123.  ,  13.05],
       [124.  ,  11.87],
       [125.  ,  12.07],
       [126.  ,  12.43],
       [127.  ,  11.79],
       [128.  ,  12.37],
       [129.  ,  12.04],
       [130.  ,  12.86],
       [131.  ,  12.88],
       [132.  ,  12.81],
       [133.  ,  12.7 ],
       [134.  ,  12.51],
       [135.  ,  12.6 ],
       [136.  ,  12.25],
       [137.  ,  12.53],
       [138.  ,  13.49],
       [139.  ,  12.84],
       [140.  ,  12.93],
       [141.  ,  13.36],
       [142.  ,  13.52],
       [143.  ,  13.62],
       [144.  ,  12.25],
       [145.  ,  13.16],
       [146.  ,  13.88],
       [147.  ,  12.87],
       [148.  ,  13.32],
       [149.  ,  13.08],
       [150.  ,  13.5 ],
       [151.  ,  12.79],
       [152.  ,  13.11],
       [153.  ,  13.23],
       [154.  ,  12.58],
       [155.  ,  13.17],
       [156.  ,  13.84],
       [157.  ,  12.45],
       [158.  ,  14.34],
       [159.  ,  13.48],
       [160.  ,  12.36],
       [161.  ,  13.69],
       [162.  ,  12.85],
       [163.  ,  12.96],
       [164.  ,  13.78],
       [165.  ,  13.73],
       [166.  ,  13.45],
       [167.  ,  12.82],
       [168.  ,  13.58],
       [169.  ,  13.4 ],
       [170.  ,  12.2 ],
       [171.  ,  12.77],
       [172.  ,  14.16],
       [173.  ,  13.71],
       [174.  ,  13.4 ],
       [175.  ,  13.27],
       [176.  ,  13.17],
       [177.  ,  14.13]])

In [84]:
y

,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...
173,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [85]:
model.fit(X_train,y_train)

LinearRegression()

In [86]:
model.score(X_test,y_test)

0.35403575546204186

In [87]:
from sklearn.metrics import r2_score

In [88]:
y_pred = model.predict(X_test)

In [89]:
r2_score(y_test,y_pred)

0.35403575546204186